name: "Central Release"
run-name: Central Release [${{ github.ref_name }}]
on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'
          check-latest: true
          server-id: 'central'
          server-username: 'CENTRAL_USERNAME'
          server-password: 'CENTRAL_TOKEN'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          cache: 'maven'

      - name: Run Tests
        run: |
          mvn test

      - name: Build & Deploy
        run: |
          mvn -U -B clean deploy -P release
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
