name: "Central Release"
run-name: Central Release [${{ github.ref_name }}]
on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'
          check-latest: true
          server-id: 'central'
          server-username: 'CENTRAL_USERNAME'
          server-password: 'CENTRAL_TOKEN'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          cache: 'maven'

      - name: Run Tests
        run: |
          mvn test

      - name: Build & Deploy
        run: |
          mvn -U -B clean deploy -P release
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
