name: "Maven Test"
run-name: Maven Test [${{ github.ref_name }}]
on:
  push:
    branches:
      - main
      - stage
      - dev
      - feature/*
      - release/*
#    workflow_dispatch:
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Install & Run Rests
        run: |
          mvn install
          mvn test
