name: "OSSRH Release"
run-name: OSSRH Release [${{ github.ref_name }}]
on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'
          check-latest: true
          server-id: 'ossrh'
          server-username: 'OSSRH_USERNAME'
          server-password: 'OSSRH_PASSWORD'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: 'GPG_PRIVATE_KEY_PASSPHRASE'
          cache: 'maven'

      - name: Run Tests
        run: |
          mvn test

      - name: Build & Deploy
        run: |
          mvn -U -B clean deploy -P release
        env:
          GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

