name: "Test and Static Code Analyze"
run-name: "Test and Static Code Analyze [${{ github.ref_name }}]"
on:
  push:
    branches:
      - main
      - 'snapshot/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'snapshot/**'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test
        run: mvn test -P test-coverage

      - name: SonarCloud analyze
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectName=${{ vars.SONAR_PROJECT_NAME }} \
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
            -Dsonar.branch.name=${{ github.ref_name }} \
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=${{ vars.SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS }} \
            -Dsonar.sources=${{ vars.SONAR_SOURCES }} \
            -Dsonar.tests=${{ vars.SONAR_TESTS }} \
            -Dsonar.exclusions=${{ vars.SONAR_EXCLUSIONS }} \
            -Dsonar.java.binaries=${{ vars.SONAR_JAVA_BINARIES }} \
            -Dsonar.coverage.exclusions=${{ vars.SONAR_COVERAGE_EXCLUSIONS }} \
            -Dsonar.java.source=17
